### ISSUE TITLE
Was ist der Unterschied zwischen LOVE und Github Issues?

### ISSUE THREAD

**Issue by f4814** [Jugendhackt/lABEr#2]
Ich denke, dass das LOVE Repository Sinnlos ist, da GitHub ein Tool für Problem/Frage Diskussionen bereitstellt, nämlich GitHub ISSUES (also das was ich gerade verwende)...

Ich schätze, dass LOVE unnötig ist

**Comment by luap42** [comment]
An sich ja, aber große Projekte nutzen so etwas auch: http://bit.ly/2dUcfxP

**Comment by f4814** [comment]
Okay, allerdings finde ich die Issues übersichtlicher

**Comment by luap42** [comment]
Andererseits ist LOVE für Entwickler übersichtlicher, jeder weiß wo etwas zu z.B. Netzwerk ist. Wenn du also die UI weiterentwickeln "möchtest", kannst du dir die LOVEs für die UI anzeigen und gute davon implementieren.

**Comment by luap42** [comment]
Ich möchte klarstellen, dass LOVE sich von Github Issues unterscheidet, da LOVEs eine detailiertere Beschreibung des Ist-Zustands erfordern und gut in Kategorien des Wird-Zustands einteilbar sind.

**Comment by tasmo** [comment]
@zoxuyu Bitte benutzte keine URL-Shortener wie Bitly o.ä. Niemand außer Dir kann vor einem Click sehen, was sich dahinter verbirgt.
Beim Entwickeln von OpenSource ist ein hoher Grad an Transparenz notwendig. Es ist dabei sinnvoll, so wenig externe Services wie möglich zu benutzen.
